SELECT 
    SUBSTR(EMAIL, INSTR(EMAIL, '@')+1) "DOMAIN",
    COUNT(*) "EA",
    (
    SELECT
        COUNT(*)
    FROM PROFESSOR
    ) "SUM_DOMAIN",
    COUNT(EMAIL) / SUM(COUNT(*)) OVER() * 100 "%"
FROM PROFESSOR
GROUP BY SUBSTR(EMAIL, INSTR(EMAIL, '@')+1)
ORDER BY SUBSTR(EMAIL, INSTR(EMAIL, '@')+1);
